create table public.astronomy_cache (
  id bigint generated by default as identity primary key,

  -- Grid/bucket used to group nearby coordinates.
  -- Example: "13.70:100.60"
  location_bucket text not null,

  -- Canonical coordinate used when requesting astronomy
  -- data for this bucket.
  latitude double precision not null,
  longitude double precision not null,

  astronomy_date date not null,

  -- LunarScope-normalized astronomy response.
  data jsonb not null,

  created_at timestamptz not null default now(),

  constraint astronomy_cache_location_date_unique
    unique (location_bucket, astronomy_date)
);

comment on table public.astronomy_cache is
  'Persistent cache for astronomy data grouped by geographic grid bucket and date';

comment on column public.astronomy_cache.location_bucket is
  'Normalized geographic bucket such as 13.70:100.60';

comment on column public.astronomy_cache.latitude is
  'Canonical latitude for the geographic bucket';

comment on column public.astronomy_cache.longitude is
  'Canonical longitude for the geographic bucket';

comment on column public.astronomy_cache.data is
  'Normalized LunarScope astronomy data, not the raw provider response';